main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from alicuota import views
# Importación de vistas
from alicuota.view.familia_view import FamiliaListView, FamiliaCreateView, FamiliaUpdateView
from alicuota.view.vivienda_view import ViviendaListView, ViviendaCreateView, ViviendaUpdateView
from alicuota.views import InicioTemplateView, LoginUserView, CustomPasswordResetView, PDFReporteResidenteView
from alicuota.view.clientes_view import *
from alicuota.view.residentes_view import ResidenteListView, ResidenteCreateView, ResidenteDeleteView, \
    ResidenteUpdateView
from alicuota.view.vehiculos_view import VehiculoListView, VehiculoCreateView, VehiculoDeleteView, VehiculoUpdateView
from alicuota.view.alicuota_view import *

urlpatterns = [
                  # URL de login
                  path('configuracion/', admin.site.urls, name="configuracion"),
                  path('api/', include('alicuota.urls')),
                  path('accounts/login/', LoginUserView.as_view(), name='custom_login'),
                  path('', RedirectView.as_view(url="accounts/login")),
                  path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),

                  # URLs de inicio
                  path('inicio/', InicioTemplateView.as_view(), name='inicio'),

                  # URLs de residentes
                  path('residente_lista/', ResidenteListView.as_view(), name='residente_lista'),
                  path('residente_crear/', ResidenteCreateView.as_view(), name='residente_crear'),
                  path('residente_eliminar/<int:pk>/', ResidenteDeleteView.as_view(), name='residente_eliminar'),
                  path('residente_actualizar/<int:pk>/', ResidenteUpdateView.as_view(), name='residente_actualizar'),
                  path('inicio/generar/<int:pk>/', PDFReporteResidenteView.as_view(), name='generar'),

                  # URLs de vehículos
                  path('vehiculos_lista/', VehiculoListView.as_view(), name='vehiculo_lista'),
                  path('vehiculo_crear/', VehiculoCreateView.as_view(), name='vehiculo_crear'),
                  path('vehiculo_eliminar/<int:pk>/', VehiculoDeleteView.as_view(), name='vehiculo_eliminar'),
                  path('vehiculo_actualizar/<int:pk>/', VehiculoUpdateView.as_view(), name='vehiculo_actualizar'),

                  # URLs de viviendas
                  path('vivienda_lista/', ViviendaListView.as_view(), name='vivienda_lista'),
                  path('vivienda_crear/', ViviendaCreateView.as_view(), name='vivienda_crear'),
                  path('vivienda_actualizar/<int:pk>/', ViviendaUpdateView.as_view(), name='vivienda_actualizar'),

                  # URLs de familias
                  path('familia_lista/', FamiliaListView.as_view(), name='familia_lista'),
                  path('familia_crear/', FamiliaCreateView.as_view(), name='familia_crear'),
                  path('familia_actualizar/<int:pk>/', FamiliaUpdateView.as_view(), name='familia_actualizar'),

                  path('alicuota_lista/', AlicuotaListView.as_view(), name='alicuota_lista'),
                  path('alicuota_crear/', AlicuotaCreateView.as_view(), name='alicuota_lista'),

                  path("__reload__/", include("django_browser_reload.urls")),
                  path("accounts/", include("django.contrib.auth.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alicuota/models.py
from django.core.exceptions import ValidationError
from django.db import models
from main import settings
from alicuota.util import *


# Modelo Para vehiculo---------------------------------------------------------------------------
class Marca(models.Model):
    nombre_marca = models.CharField(
        max_length=50, verbose_name="Nombre de la Marca",
        blank=False, null=False, unique=True
    )

    def __str__(self):
        return self.nombre_marca


class Modelo(models.Model):
    nombre_modelo = models.CharField(
        max_length=50, verbose_name="Nombre del Modelo",
        blank=False, null=False, unique=True
    )
    marca = models.ForeignKey(
        Marca, on_delete=models.CASCADE,
        verbose_name="Marca",
        related_name='modelos',
        blank=False, null=False
    )

    def __str__(self):
        return f"{self.nombre_modelo} - {self.marca}"


class Vehiculo(models.Model):
    modelo = models.ForeignKey(
        Modelo, on_delete=models.CASCADE,
        verbose_name="Modelo",
        related_name='vehiculos',
        blank=False, null=False
    )
    placa = models.CharField(
        max_length=50, verbose_name="Placa",
        blank=False, null=False, unique=True
    )
    anio = models.PositiveIntegerField(
        verbose_name="Año",
        blank=False, null=False
    )
    color = models.CharField(
        max_length=50, verbose_name="Color",
        blank=False, null=False
    )

    def __str__(self):
        return f"{self.placa} - {self.modelo}"


# Modelo de TipoResidente----------------------------------------------------------------
class TipoResidente(models.Model):
    descripcion = models.CharField(
        max_length=50,
        verbose_name="Descripción",
        blank=False,
        null=False
    )

    def __str__(self):
        return self.descripcion


# Modelo Residente ---------------------------------------------------------------------------------

class Residente(models.Model):
    tipo_residente = models.ForeignKey(
        TipoResidente, on_delete=models.CASCADE,
        verbose_name="Tipo Residente",
        related_name='residentes',
        blank=False,
        null=False
    )
    vehiculo = models.ForeignKey(
        Vehiculo, on_delete=models.SET_NULL,
        verbose_name="Vehículo",
        null=True,
        blank=True,
        related_name='residentes'
    )
    nombre = models.CharField(
        max_length=50,
        verbose_name="Nombre Residente",
        blank=False,
        null=False
    )
    telefono = models.CharField(
        max_length=10,
        verbose_name="Teléfono",
        blank=False,
        null=False, unique=True, validators=[solo_numeros_validator]
    )
    email = models.EmailField(
        max_length=50,
        verbose_name="Email",
        blank=False,
        null=False, unique=True
    )
    cedula = models.CharField(
        max_length=10,
        verbose_name="Cédula",
        blank=False,
        null=False, unique=True, validators=[validar_cedula_ecuatoriana, solo_numeros_validator],
    )
    # Nuevo campo status para indicar si es residente o cliente
    status = models.BooleanField(
        default=True,  # True indica que es residente, False indica que es cliente
        verbose_name="Estado",
    )

    def get_status_display(self):
        return "Residente" if self.status else "Cliente"

    def __str__(self):
        vehiculo_texto = 'Con vehículo' if self.vehiculo else "Sin vehículo"
        return f"{self.nombre} ({self.cedula}) - Vehículo: {vehiculo_texto} - {self.get_status_display()}"


# Modelo Urbanizacion
class Urbanizacion(models.Model):
    nombre_urbanizacion = models.CharField(max_length=50, blank=False, null=False, unique=True)
    direccion = models.CharField(max_length=50, blank=False, null=False)

    def __str__(self):
        return self.nombre_urbanizacion

    class Meta:
        verbose_name = "Urbanización"
        verbose_name_plural = "Urbanizaciones"


# Modelo de Manzana
class Manzana(models.Model):
    urbanizacion = models.ForeignKey(Urbanizacion, on_delete=models.CASCADE, blank=False,
                                     null=False)
    codigo_manzana = models.CharField(max_length=50, blank=False, null=False)

    def __str__(self):
        return self.codigo_manzana


# Modelo de Villa
class Villa(models.Model):
    manzana = models.ForeignKey(Manzana, on_delete=models.CASCADE, blank=False,
                                null=False)
    numero_villa = models.CharField(max_length=50, blank=False, null=False, unique=True)

    def __str__(self):
        return f'{self.numero_villa} - {self.manzana.codigo_manzana}'


# Modeo Tipo Vivienda
class TipoVivienda(models.Model):
    descripcion = models.CharField(max_length=50, blank=False, null=False)

    def __str__(self):
        return self.descripcion


# Modelo Tasa de Interez
class TasaInterez(models.Model):
    porcentaje = models.IntegerField()

    def clean(self):
        if self.porcentaje < 0 or self.porcentaje > 99:
            raise ValidationError('El porcentaje debe estar entre 0 y 99.')

    def __str__(self):
        return f"{self.porcentaje}%"


# Modelo Tasa de Entrada
class TasaEntrada(models.Model):
    porcentaje = models.IntegerField()

    def clean(self):
        if self.porcentaje < 0 or self.porcentaje > 99:
            raise ValidationError('El porcentaje debe estar entre 0 y 99.')

    def __str__(self):
        return f"{self.porcentaje}%"


# Modelo Vivienda
class Vivienda(models.Model):
    tipovivienda = models.ForeignKey(TipoVivienda, on_delete=models.CASCADE, blank=False, null=False)
    residente = models.ForeignKey('Residente', on_delete=models.CASCADE, blank=True, null=True)
    villa = models.ForeignKey(Villa, on_delete=models.CASCADE, blank=False, null=False)
    descripcion = models.CharField(max_length=50, blank=False, null=False)
    habitaciones = models.IntegerField(blank=False, null=False)
    banos = models.IntegerField(blank=False, null=False)
    valor = models.DecimalField(max_digits=10, decimal_places=2, blank=False, null=False)
    metros_cuadrados = models.DecimalField(max_digits=10, decimal_places=2, blank=False, null=False)
    imagen = models.FileField(upload_to='logo/vivienda', blank=True, null=True)
    estado = models.BooleanField(default=True, help_text="Estado de disponibilidad de la vivienda")

    def __str__(self):
        if self.residente:
            return f"{self.descripcion} - {self.residente.nombre}"
        return f"{self.descripcion} - Sin residente"

    def get_image(self):
        if self.imagen:
            return f"{settings.MEDIA_URL}{self.imagen}"
        return f"{settings.STATIC_URL}img/empty.jpg"

    def estado_display(self):
        return "Ocupada" if self.estado else "Disponible"


# Model familia residente
class FamiliaPropietario(models.Model):
    residente = models.ForeignKey(Residente, on_delete=models.CASCADE)
    descripcion = models.CharField(max_length=50, blank=False, null=False)

    def __str__(self):
        return f"Familia de {self.residente}"


class MiembroFamilia(models.Model):
    familia = models.ForeignKey(FamiliaPropietario, on_delete=models.CASCADE, related_name="miembros")
    nombre = models.CharField(max_length=50, blank=False, null=False)
    cedula = models.CharField(max_length=10, unique=True, null=False, blank=False)
    sexo = models.CharField(max_length=50, blank=False, null=False)
    fecha_nacimiento = models.DateField(blank=False, null=False)
    parentesco = models.CharField(max_length=50, blank=False, null=False)

    def __str__(self):
        return f"{self.nombre} ({self.parentesco})"


# Modeo Alicuota - Cabecera de la alicuota
class CabAlicuota(models.Model):
    vivienda = models.ForeignKey(Vivienda, on_delete=models.CASCADE)
    Interes = models.ForeignKey(TasaInterez, on_delete=models.CASCADE)
    entrada_tasa = models.ForeignKey(TasaEntrada, on_delete=models.CASCADE)
    pago_inicial = models.DecimalField(max_digits=10, decimal_places=2)
    saldo_pagar = models.IntegerField()
    fecha_creacion = models.DateField()
    fecha_pago = models.CharField(max_length=50, blank=False, null=False)
    periodo = models.IntegerField()# Las letras que se van a diferir en la alicuota
    monto = models.DecimalField(max_digits=10, decimal_places=2)# Monto que se trae de la vivienda
    saldo_financiar = models.DecimalField(max_digits=10, decimal_places=2)
    saldo_pendiente = models.DecimalField(max_digits=10, decimal_places=2)# Saldo Pendiente de las letras que se van cancelando

    def __str__(self):
        return f"{self.nombre} ({self.monto})({self.tasa_interez})({self.periodo})"

# Detalle alicuota
class DetAlicuota(models.Model):
    cab_alicuota = models.ForeignKey(CabAlicuota, on_delete=models.CASCADE)
    secuencia = models.IntegerField()
    fecha = models.DateField()
    fecha_vencimiento = models.DateField()
    recargo = models.DecimalField(max_digits=10, decimal_places=2)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    saldo_pagar = models.DecimalField(max_digits=10, decimal_places=2)
    estado = models.DecimalField(max_digits=10, decimal_places=2)

templates/Familia_Residente/crear_familia.html
{% extends 'base.html' %}
{% load static %}
{% block contenido %}
<div class="max-w-8xl mx-auto bg-white p-6 rounded-lg shadow-lg">
    <h1 class="text-3xl font-bell mb-6 text-center">{{ titulo }}</h1>
    <form method="POST" action="{{ action_save }}">
        {% csrf_token %}

        <!-- Selector de residente -->
        <div class="mb-6">
            <label for="residente" class="block text-lg font-bell mb-2 text-gray-700">Seleccione el
                Residente:</label>
            <select class="w-full border border-gray-300 p-2 rounded-md" id="id_residente" required>
                <option selected disabled value="">Seleccione un Residente</option>
                {% for residente in residentes %}
                <option value="{{ residente.id }}">{{ residente.nombre }} - {{ residente.cedula }}</option>
                {% endfor %}
            </select>
        </div>

        <!-- Campo Descripción -->
        <div class="mb-6">
            <label for="descripcion" class="block text-lg font-bell mb-2 text-gray-700">Descripción:</label>
            <input class="w-full border border-gray-300 p-2 rounded-md" type="text" id="id_descripcion" required>
        </div>

        <!-- Tabla de miembros de la familia -->
        <div class="overflow-x-auto">
            <table class="w-full text-left table-auto border-collapse bg-white shadow-lg rounded-lg" id="familia">
                <thead class="text-center">
                    <tr class="bg-gray-300">
                        <th class="p-3 border">Nombre</th>
                        <th class="p-3 border">Cédula</th>
                        <th class="p-3 border">Sexo</th>
                        <th class="p-3 border">Parentesco</th>
                        <th class="p-3 border">Fecha de Nacimiento</th>
                        <th class="p-3 border">Acción</th>
                    </tr>
                </thead>
                <tbody>

                </tbody>
                <tr class="bg-gray-300">
                    <td class="p-3 border">
                        <input class="" type="text" id="nombre" placeholder="Nombre" required>
                    </td>
                    <td class="p-3 border">
                        <input class="form-control" type="text" id="cedula" placeholder="Cédula" required>
                    </td>
                    <td class="p-3 border">
                        <select class="form-control" id="sexo" required>
                            <option value="">Sexo</option>
                            <option value="Masculino">Masculino</option>
                            <option value="Femenino">Femenino</option>
                        </select>
                    </td>
                    <td class="p-3 border">
                        <select class="form-control" id="parentesco" required>
                            <option value="">Parentesco</option>
                            <option value="Hermano">Hermano</option>
                            <option value="Hermana">Hermana</option>
                            <option value="Padre">Padre</option>
                            <option value="Madre">Madre</option>
                            <option value="Abuelo">Abuelo</option>
                            <option value="Abuela">Abuela</option>
                            <option value="Conyuge">Conyuge</option>
                            <option value="Hijo">Hijo</option>
                            <option value="Hija">Hija</option>
                        </select>
                    </td>
                    <td class="p-3 border">
                        <input class="form-control" type="date" id="fecha-nacimiento" required>
                    </td>
                    <td class="p-3 border flex justify-center h-full">
                        <a class="bg-blue-500 text-white py-2 px-4 rounded-md shadow-md hover:bg-blue-600
							focus:outline-none" onclick="agregarPersona()">Agregar
                        </a>
                    </td>
                </tr>
            </table>

            <p class="mt-4 text-lg font-bold">Total de miembros: <span id="contadorMiembros"></span></p>
        </div>
        <!-- Botones de acción -->
        <div class="flex justify-between mt-6 space-x-2">
            <a href="{{ cancel_url }}"
                class="w-1/2 bg-red-500 text-white py-2 rounded-md shadow-md hover:bg-red-600 focus:outline-none text-center">Cancelar</a>
            <a class="w-1/2 bg-green-500 text-white py-2 rounded-md shadow-md hover:bg-green-600
				focus:outline-none text-center" onclick="comsumirApi()">
                Guardar Familia
            </a>
        </div>
    </form>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript" src="{% static 'JS/crear_familia.js' %}"></script>
{% endblock %}

templates/Familia_Residente/editar_familia.html
{% extends 'base.html' %}
{% load static %}
{% block contenido %}
<div class="max-w-8xl mx-auto bg-white p-6 rounded-lg shadow-lg">
  <h1 class="text-3xl font-bell mb-6 text-center">{{ titulo }}</h1>
  <form method="POST">

    <!-- Selector de residente -->
    <div class="mb-6">
      <label for="residente" class="block text-lg font-bell mb-2 text-gray-700">Seleccione el
        Residente:</label>
      <input class="w-full border  bg-gray-100 border-gray-300 p-2 rounded-md" type="text" id="residente"
        value="{{propietario.residente}}" disabled>
    </div>
    <input class="w-full border  bg-gray-100 border-gray-300 p-2 rounded-md hidden" type="text" id="id_residente"
      value="{{propietario.id}}" disabled>
    <!-- Campo Descripción -->
    <div class="mb-6">
      <label for="descripcion" class="block text-lg font-bell mb-2 text-gray-700">Descripción:</label>
      <input class="w-full border border-gray-300 p-2 rounded-md" type="text" id="id_descripcion"
        value="{{propietario.descripcion}}">
    </div>

    <!-- Tabla de miembros de la familia -->
    <div class="overflow-x-auto">
      <table class="w-full text-left table-auto border-collapse bg-white shadow-lg rounded-lg" id="familia">
        <thead class="text-center">
          <tr class="bg-gray-300">
            <th class="p-3 border">Nombre</th>
            <th class="p-3 border">Cédula</th>
            <th class="p-3 border">Sexo</th>
            <th class="p-3 border">Parentesco</th>
            <th class="p-3 border">Fecha de Nacimiento</th>
            <th class="p-3 border">Acción</th>
          </tr>
        </thead>
        <tbody>

        </tbody>
        <tr class="bg-gray-300">
          <td class="p-3 border">
            <input class="" type="text" id="nombre" placeholder="Nombre" required>
          </td>
          <td class="p-3 border">
            <input class="form-control" type="text" id="cedula" placeholder="Cédula" required>
          </td>
          <td class="p-3 border">
            <select class="form-control" id="sexo" required>
              <option value="">Sexo</option>
              <option value="Masculino">Masculino</option>
              <option value="Femenino">Femenino</option>
            </select>
          </td>
          <td class="p-3 border">
            <select class="form-control" id="parentesco" required>
              <option value="">Parentesco</option>
              <option value="Hermano">Hermano</option>
              <option value="Hermana">Hermana</option>
              <option value="Padre">Padre</option>
              <option value="Madre">Madre</option>
              <option value="Abuelo">Abuelo</option>
              <option value="Abuela">Abuela</option>
              <option value="Conyuge">Conyuge</option>
              <option value="Hijo">Hijo</option>
              <option value="Hija">Hija</option>
            </select>
          </td>
          <td class="p-3 border">
            <input class="form-control" type="date" id="fecha-nacimiento" required>
          </td>
          <td class="p-3 border flex justify-center h-full">
            <a class="bg-blue-500 text-white py-2 px-4 rounded-md shadow-md hover:bg-blue-600
							focus:outline-none" onclick="agregarPersona()">Agregar
            </a>
          </td>
        </tr>
      </table>

      <p class="mt-4 text-lg font-bold">Total de miembros: <span id="contadorMiembros"></span></p>
    </div>
    <!-- Botones de acción -->
    <div class="flex justify-between mt-6 space-x-2">
      <a href="{{ cancel_url }}"
        class="w-1/2 bg-red-500 text-white py-2 rounded-md shadow-md hover:bg-red-600 focus:outline-none text-center">Cancelar</a>
      <a href="{{ guardar_url }}" class="w-1/2 bg-green-500 text-white py-2 rounded-md shadow-md hover:bg-green-600
				focus:outline-none text-center" onclick="comsumirApi()">
        Modificar Familia
      </a>
    </div>
  </form>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript" src="{% static 'JS/editar_familia.js' %}"></script>
{% endblock %}

templates/Familia_Residente/lista_familia.html
{% extends 'listado.html' %}
{% block contenido %}
<div class="max-w-5xl mx-auto bg-white p-6 rounded-lg shadow-lg mb-8">
	<h1 class="text-3xl font-semibold mb-6 text-center text-blue-700">{{ titulo }}</h1>
	<!-- Barra de búsqueda -->
	<div class="flex flex-col sm:flex-row justify-between items-center mb-6 gap-4">
		<div class="flex flex-wrap w-full sm:w-auto gap-2">
			<form method="GET" action="">
				<input type="text" placeholder="Buscar Vivienda..."
					class="w-full sm:w-80 px-4 py-2 border border-gray-300 rounded-l-md focus:outline-none focus:ring-2 focus:ring-indigo-400" />
				<button class="bg-gray-700 text-white px-4 py-2 rounded-r-md hover:bg-gray-900 focus:outline-none">
					Buscar
				</button>
			</form>
		</div>
		<a href="{{ url_crear }}" class="flex items-center bg-gray-700 text-white px-4 py-2 rounded-md hover:bg-gray-900">
			<i class="bi bi-node-plus mr-2"></i>Añadir Familia
		</a>
	</div>
	<!-- Tabla de residentes -->
	<div>
		<table class="w-full text-left border border-gray-300">
			<thead>
				<tr>
					<th class="py-2 text-center font-medium border-b">Residente</th>
					<th class="py-2 text-center font-medium border-b">Nombre Familia</th>
					<th class="py-2 text-center font-medium border-b">Opción</th>
				</tr>
			</thead>
			<tbody id="resident-list" class="space-y-4">
				{% for object in object_list %}
				<tr class="border-b">
					<td class="text-center border-b">
						<span class="font-medium">{{ object.residente }}</span>
					</td>
					<td class="text-center border-b">
						<p>Familia: {{ object.descripcion }}</p>
					</td>
					<td class="text-center border-b space-x-2">
						<button
							class="show-family-info bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600 focus:outline-none"
							onclick="mostrarModal({{ object.id }})">Detalle
						</button>
						<a href="{% url 'familia_actualizar' object.id %}"
							class="px-4 py-2 bg-custom-green text-white rounded-md hover:bg-green-800 text-center">
							Editar
						</a>
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>

		<!-- Modal Template -->
		{% for object in object_list %}
		<div id="modal{{ object.id }}"
			class="hidden fixed inset-0 bg-gray-900 bg-opacity-50 flex justify-center items-center">
			<div class="bg-white p-6 rounded-lg shadow-lg max-w-lg w-full overflow-hidden">
				<h2 class="text-xl font-bold mb-4 text-center">Información de la Familia
					de {{ object.residente }}</h2>
				<p class="text-center font-bell mb-4">Detalles de los miembros de la familia</p>
				<div class="overflow-hidden">
					<table class="w-full text-left border-collapse">
						<thead>
							<tr class="bg-gray-200">
								<th class="font-semibold border px-2 py-1">Nombre</th>
								<th class="font-semibold border px-2 py-1">Cédula</th>
								<th class="font-semibold border px-2 py-1">Sexo</th>
								<th class="font-semibold border px-2 py-1">Parentesco</th>
								<th class="font-semibold border px-2 py-1">Fecha de Nacimiento</th>
							</tr>
						</thead>
						<tbody>
							{% for miembro in object.miembros.all %}
							<tr>
								<td class="border px-2 py-1">{{ miembro.nombre }}</td>
								<td class="border px-2 py-1">{{ miembro.cedula }}</td>
								<td class="border px-2 py-1">{{ miembro.sexo }}</td>
								<td class="border px-2 py-1">{{ miembro.parentesco }}</td>
								<td class="border px-2 py-1">{{ miembro.fecha_nacimiento }}</td>
							</tr>
							{% empty %}
							<tr>
								<td colspan="5" class="border px-2 py-1 text-center">No hay miembros en esta
									familia.
								</td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
				<div class="flex justify-center mt-4">
					<button class="bg-red-500 text-white px-4 py-2 rounded-md hover:bg-red-600 focus:outline-none"
						onclick="ocultarModal({{ object.id }})">Cerrar
					</button>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
</div>
<script>
	function mostrarModal(id) {
		document.getElementById('modal' + id).classList.remove('hidden');
	}

	function ocultarModal(id) {
		document.getElementById('modal' + id).classList.add('hidden');
	}
</script>
{% endblock %}